1. 导入numpy库，并命名为np，打印numpy版本

In [1]:
import numpy as np

print(np.__version__)

1.24.3


2. 使用数值n=1000000对比python原生列表跟numpy计算的时差

In [ ]:
import time

n = 1000000
start_time = time.time()
python_list = list(range(n))

for i in range(n):
    python_list[i] += 1
python_time = time.time() - start_time
print(f'python列表执行的时间为:{python_time:6f}秒')

start_time = time.time()
numpy_array = np.arange(n)
numpy_array += 1
numpy_time = time.time() - start_time
print(f'numpy执行的时间为:{numpy_time:6f}秒')

final = python_time/numpy_time
print(f'numpy比python列表快{final:.2f}倍')

3. 创建一个大小为10的空向量

In [4]:
array = np.zeros(10)
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4. 如何找到任意数组的内存大小

In [7]:
array = np.zeros((10,10))
array.size * array.itemsize
array.nbytes

800

5. 创建两个数组，分别指定32位的单精度浮点数和字符串类型

In [10]:
array = np.array([[1,2,3],[4,5,6]],dtype = np.float32)
print(array.dtype)

array_str = np.array(['python', 'php', 'java'],dtype = np.string_)
print(array_str.dtype)

float32
|S6


6. 创建一个大小为10的空向量，但第五个值为1

In [12]:
array = np.zeros(10)
array[4] = 1
array

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

7. 创建一个值，范围从10到49的向量

In [13]:
array = np.arange(10, 50)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

8. 反转一个向量（第一个元素变为最后一个）

In [16]:
array = np.arange(10)
array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

9. 创建一个3x3的矩阵，值范围从0到8

In [17]:
array = np.arange(9).reshape(3, 3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. 找到非零元素在[1,2,0,0,4,0]中的索引

In [18]:
nz = np.nonzero([1,2,0,0,4,0])
nz

(array([0, 1, 4], dtype=int64),)

11. 创建一个3*3的单位矩阵

In [22]:
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

12. 创建一个大小为3*3*3的随机值数组

In [23]:
array = np.random.random((3, 3, 3))
array

array([[[0.45341364, 0.61820213, 0.08214266],
        [0.82059168, 0.8595467 , 0.64829908],
        [0.81445102, 0.48064237, 0.63892037]],

       [[0.10636492, 0.95907926, 0.78220473],
        [0.07074941, 0.81289857, 0.39680274],
        [0.60106253, 0.14760891, 0.27176289]],

       [[0.20314386, 0.6512686 , 0.57976693],
        [0.14358746, 0.11267608, 0.41215654],
        [0.82259659, 0.35311253, 0.43022769]]])

13. 创建一个10*10的随机值数组，并找到最小值和最大值

In [27]:
array = np.random.random((10, 10))
print(array.min(), array.max())

0.0037528096920537157 0.9929186076855461


14. 创建一个大小为30的随机向量，并找到平均值

In [29]:
array = np.random.random(30)
m = array.mean()
print(array)
print(m)

[0.73620241 0.5509654  0.07965101 0.81726449 0.30718505 0.68250316
 0.54071996 0.54668838 0.77126505 0.73621427 0.12915226 0.06183078
 0.6385372  0.10943325 0.15548373 0.9205234  0.83776483 0.18833677
 0.07216106 0.45681491 0.16531491 0.26677528 0.40667596 0.73179849
 0.72470433 0.93972469 0.05412905 0.00362386 0.61903039 0.14059162]
0.4463688644318282


15. 创建一个二维数组，边界为1，内部为0

In [31]:
array = np.ones((10, 10))
array[1:-1, 1:-1] = 0
array

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

16. 如何在现有数组周围添加一个填充为0的边界？

In [34]:
# array = np.array([1, 2, 3])
# zero_arr = np.zeros((3, len(array) + 2))

# zero_arr[1,1:-1] = array
# print(zero_arr)

arr = np.ones((3,3))
array = np.pad(arr, pad_width=1, constant_values = 0)
print(array)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


17. 创建一个5*5的矩阵，值为1,2,3,4,5,位于对角线下方

In [38]:
array = np.diag(1+np.arange(5), k=0)
print(array)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


18. 创建一个8*8的矩阵，要求行列分别为0,1交替出现

In [43]:
array = np.zeros((8,8),dtype=int)
array[1::2, ::2] = 1
array[::2,1::2] = 1
print(array)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


19. 一个shape为(6,7,8)的数组，第100个元素的索引(x,y,z)是什么？

In [44]:
shape = (6,7,8)
index = 99
res = np.unravel_index(99,shape)
print(res)

(1, 5, 3)
